name: politicon
favicon: null
layout_spectrum: 0.6165374300908297
typography_spectrum: 0.007062201388180256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9885323962662369
  lightness: 0.3264272704254836
  saturation: 0.8754790332168341
  rhythmicContrast: 0.6095470851287246
purpose: []
